version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energybench-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - energybench-network

  # Development server (alternative to production build)
  frontend-dev:
    image: node:20-alpine
    container_name: energybench-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - energybench-network
    profiles:
      - development

networks:
  energybench-network:
    driver: bridge
